# Generated by Django 4.1 on 2022-08-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_predator_alter_sighting_options_alter_sighting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='predators',
            field=models.ManyToManyField(to='main_app.predator'),
        ),
    ]
